"""Data catalog part 3 for issues 42 to 62."""

from typing import Any, Dict, List

ISSUES_DATA_PART3: List[Dict[str, Any]] = [
    # =========================================================================
    # DOMAIN 11: CI/CD (Issues 42 - 44) -> Milestone: Phase 18
    # =========================================================================
    {
        "num": 42,
        "domain": "CI/CD",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["ci", "testing"],
        "title": "Add GitHub Actions workflow for automated testing, linting, formatting, and type checks",
        "problem": "The repository completely lacks `.github/workflows/`. Pull requests and commits are not validated by automated CI checks.",
        "current_state": "No CI configuration files exist in `.github/`.",
        "proposed_change": "Create `.github/workflows/ci.yml` using `astral-sh/setup-uv`, running `ruff check`, `ruff format --check`, `mypy src/`, and `pytest` on push and pull request.",
        "scope": "Adds CI workflow configuration file.",
        "acceptance_criteria": [
            "GitHub Actions workflow triggers on push to `main` and all pull requests.",
            "Runs lint, format, type checks, and pytest test suite.",
            "Workflow badge added to `README.md`.",
        ],
        "relevant_files": [
            ".github/workflows/ci.yml",
            "README.md",
        ],
        "notes": "Essential foundation for reliable collaborative development.",
    },
    {
        "num": 43,
        "domain": "CI/CD",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["ci", "testing"],
        "title": "Add Python multi-version test matrix (3.10, 3.11, 3.12, 3.13, 3.14) to CI pipeline",
        "problem": "Local development occurs on Python 3.14, but `pyproject.toml` supports Python `>=3.10`. Without matrix testing, version-specific regressions may go unnoticed.",
        "current_state": "No matrix configuration exists.",
        "proposed_change": "Configure a matrix strategy in `.github/workflows/ci.yml` covering Python versions 3.10, 3.11, 3.12, 3.13, and 3.14 across Ubuntu runners.",
        "scope": "Expands CI workflow matrix.",
        "acceptance_criteria": [
            "Test matrix runs across Python 3.10 through 3.14.",
            "All unit and integration tests pass on every supported Python version.",
            "Matrix failures block merging.",
        ],
        "relevant_files": [
            ".github/workflows/ci.yml",
            "pyproject.toml",
        ],
        "notes": "Ensures wide compatibility across research lab environments.",
    },
    {
        "num": 44,
        "domain": "CI/CD",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["ci", "testing"],
        "title": "Add automated test coverage reporting with codecov integration in pull requests",
        "problem": "While `pytest-cov` is configured in `pyproject.toml`, test coverage reports are not uploaded or enforced during code review.",
        "current_state": "`pytest-cov` flags are defined, but coverage XMLs are not published to an external tracker.",
        "proposed_change": "Integrate Codecov or GitHub Actions step summary to publish statement coverage percentages on every PR.",
        "scope": "Updates CI workflow and coverage reporting configuration.",
        "acceptance_criteria": [
            "Coverage report XML is generated during CI test execution.",
            "PR comments or step summaries display coverage changes.",
            "Minimum 80% coverage threshold is enforced.",
        ],
        "relevant_files": [
            ".github/workflows/ci.yml",
            "pyproject.toml",
        ],
        "notes": "Maintains high testing discipline as the codebase grows.",
    },
    # =========================================================================
    # DOMAIN 12: PACKAGING & RELEASE ENGINEERING (Issues 45 - 47) -> Milestone: Phase 22
    # =========================================================================
    {
        "num": 45,
        "domain": "Packaging & Release Engineering",
        "milestone": "Phase 22 — Release Engineering",
        "labels": ["packaging", "quality"],
        "title": "Standardize ruff formatting across all repository modules to pass strict formatting checks",
        "problem": "Running `uv run ruff format --check .` flags 6 unformatted files, failing strict CI formatting gates.",
        "current_state": "Files `src/adaptive_rl/cli.py`, `config.py`, `astar.py`, `rrt_star.py`, and test files have lines exceeding 100 characters or divergent formatting.",
        "proposed_change": "Run `uv run ruff format .` and enforce formatting checks in pre-commit and CI.",
        "scope": "Formats source files without changing runtime logic.",
        "acceptance_criteria": [
            "`uv run ruff format --check .` exits with code 0 across 100% of repository files.",
            "Zero semantic or functional changes introduced.",
        ],
        "relevant_files": [
            "src/adaptive_rl/cli.py",
            "src/adaptive_rl/config.py",
            "src/adaptive_rl/planners/astar.py",
            "src/adaptive_rl/planners/rrt_star.py",
        ],
        "notes": "Cleans up formatting tech debt.",
    },
    {
        "num": 46,
        "domain": "Packaging & Release Engineering",
        "milestone": "Phase 22 — Release Engineering",
        "labels": ["packaging", "ci"],
        "title": "Add automated wheel build verification and package installation smoke tests to release workflow",
        "problem": "No automated test verifies that `pip install dist/*.whl` succeeds in a clean environment and CLI entry points execute properly.",
        "current_state": "`pyproject.toml` defines setuptools packaging, but release build artifacts are not validated automatically.",
        "proposed_change": "Add `.github/workflows/release_check.yml` that builds sdist and wheel artifacts using `uv build` and tests installation in an isolated sandbox.",
        "scope": "Adds release artifact verification workflow.",
        "acceptance_criteria": [
            "`uv build` produces valid source distribution and wheel packages.",
            "Wheel installs in a clean Python container without dependency conflicts.",
            "`adaptive-rl --version` executes cleanly from the installed wheel.",
        ],
        "relevant_files": [
            ".github/workflows/release_check.yml",
            "pyproject.toml",
        ],
        "notes": "Prevents publishing broken releases to PyPI.",
    },
    {
        "num": 47,
        "domain": "Packaging & Release Engineering",
        "milestone": "Phase 22 — Release Engineering",
        "labels": ["packaging", "architecture"],
        "title": "Define modular optional dependency groups for minimal core, RL, and visualization extras",
        "problem": "Users installing minimal core packages receive obscure import errors if they accidentally trigger RL or visualization commands.",
        "current_state": "`pyproject.toml` defines `[project.optional-dependencies]` (`rl`, `dev`, `all`), but error handling for missing optional packages is uneven.",
        "proposed_change": "Provide clear lazy-import guards and user-friendly error messages instructing users to install `adaptive-rl[rl]` or `adaptive-rl[all]` when missing dependencies are detected.",
        "scope": "Adds import guard utilities in `src/adaptive_rl/utils/imports.py` and applies them to CLI and training modules.",
        "acceptance_criteria": [
            "Attempting to run training without `torch`/`sb3` prints `Install adaptive-rl[rl] to enable training`.",
            "Core planner and environment utilities run with zero PyTorch dependencies.",
            "Tests verify helpful error messages on missing optional extras.",
        ],
        "relevant_files": [
            "pyproject.toml",
            "src/adaptive_rl/cli.py",
            "src/adaptive_rl/training/__init__.py",
        ],
        "notes": "Ensures clean lightweight deployments on constrained edge devices.",
    },
    # =========================================================================
    # DOMAIN 13: DOCUMENTATION & OPEN SOURCE (Issues 48 - 51) -> Milestone: Phase 21
    # =========================================================================
    {
        "num": 48,
        "domain": "Documentation & Open Source",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["documentation"],
        "title": "Add GitHub issue templates and pull request template for bug reports, features, and research proposals",
        "problem": "The repository lacks GitHub issue and PR templates, leading to incomplete bug reports and unstructured contributor PRs.",
        "current_state": "`.github/ISSUE_TEMPLATE/` and `.github/pull_request_template.md` do not exist.",
        "proposed_change": "Create issue templates for Bug Reports, Feature Requests, and Benchmark Reproductions, plus a standardized PR template with a quality checklist.",
        "scope": "Adds markdown templates under `.github/`.",
        "acceptance_criteria": [
            "Bug report template prompts for environment info, reproduction script, and logs.",
            "Feature request template prompts for motivation and proposed API.",
            "PR template includes checklists for tests, typing, and docs.",
        ],
        "relevant_files": [
            ".github/ISSUE_TEMPLATE/bug_report.md",
            ".github/ISSUE_TEMPLATE/feature_request.md",
            ".github/pull_request_template.md",
        ],
        "notes": "Fosters high-quality open-source community contributions.",
    },
    {
        "num": 49,
        "domain": "Documentation & Open Source",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["documentation", "architecture"],
        "title": "Add comprehensive architectural guide and component interaction diagram in documentation",
        "problem": "New contributors must deduce the relationships between `ExperimentManager`, `Evaluator`, `BenchmarkRunner`, and registries by reading code.",
        "current_state": "`README.md` provides an overview, but no architectural deep-dive or Mermaid sequence diagrams exist.",
        "proposed_change": "Create `docs/ARCHITECTURE.md` with Mermaid diagrams illustrating configuration parsing, environment lifecycle, training dispatch, and metric standardization.",
        "scope": "Adds architectural reference document under `docs/`.",
        "acceptance_criteria": [
            "`docs/ARCHITECTURE.md` documents module responsibilities and boundaries.",
            "Includes Mermaid sequence diagram for experiment execution.",
            "Linked from `README.md` and `CONTRIBUTING.md`.",
        ],
        "relevant_files": [
            "docs/ARCHITECTURE.md",
            "README.md",
            "CONTRIBUTING.md",
        ],
        "notes": "Lowers contributor barrier to entry.",
    },
    {
        "num": 50,
        "domain": "Documentation & Open Source",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["documentation", "environments"],
        "title": "Add step-by-step tutorial for adding custom Gymnasium environments to AdaptiveRL",
        "problem": "Researchers wanting to add custom environments (e.g. robotic manipulation or multi-agent traffic) have no guide for integrating with AdaptiveRL registries.",
        "current_state": "No dedicated environment contribution tutorial exists.",
        "proposed_change": "Write `docs/CUSTOM_ENVIRONMENT_GUIDE.md` detailing step signature, info dict requirements, metadata registration, and conformance testing.",
        "scope": "Adds environment developer guide with a fully runnable template.",
        "acceptance_criteria": [
            "Guide explains observation normalization and reward structuring best practices.",
            "Includes copy-pasteable minimal custom environment example.",
            "Explains registry integration and Gymnasium compliance testing.",
        ],
        "relevant_files": [
            "docs/CUSTOM_ENVIRONMENT_GUIDE.md",
            "README.md",
        ],
        "notes": "Empowers researchers to bring their own robotics benchmarks into AdaptiveRL.",
    },
    {
        "num": 51,
        "domain": "Documentation & Open Source",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["documentation", "planners"],
        "title": "Add step-by-step tutorial for implementing new classical motion planners and baseline adapters",
        "problem": "Adding classical baselines (e.g. PRM, D* Lite, or Hybrid A*) lacks documentation explaining `PlannerResult`, validation, and `PlannerAdapter` integration.",
        "current_state": "Existing planners are documented in code docstrings, but no guide exists for contributors.",
        "proposed_change": "Create `docs/PLANNER_GUIDE.md` detailing planner base class inheritance, collision validation protocol, and benchmarking integration.",
        "scope": "Adds documentation guide under `docs/`.",
        "acceptance_criteria": [
            "Step-by-step guide on implementing `BasePlanner` subclasses.",
            "Explains how `PlannerAdapter` extracts environmental obstacles and start/goal positions.",
            "Details standardized metric reporting requirements.",
        ],
        "relevant_files": [
            "docs/PLANNER_GUIDE.md",
            "README.md",
        ],
        "notes": "Encourages contributions of diverse classical planning baselines.",
    },
    # =========================================================================
    # DOMAIN 14: PERFORMANCE & PROFILING (Issues 52 - 54) -> Milestone: Phase 20
    # =========================================================================
    {
        "num": 52,
        "domain": "Performance & Profiling",
        "milestone": "Phase 20 — Performance & Scaling",
        "labels": ["performance", "environments"],
        "title": "Profile and optimize 2D continuous navigation LiDAR raycasting and collision checks",
        "problem": "In `ContinuousNavigation2DEnv`, LiDAR raycasting checks every ray against every circular obstacle sequentially, taking up >60% of step time.",
        "current_state": "In `src/adaptive_rl/environments/navigation/navigation2d.py`, ray-circle intersection math is evaluated in pure Python loops for all rays.",
        "proposed_change": "Vectorize LiDAR ray-circle intersection tests using NumPy broadcasting or lightweight spatial bounding boxes, reducing per-step latency.",
        "scope": "Optimizes `_compute_lidar()` in `navigation2d.py` without altering returned sensor readings.",
        "acceptance_criteria": [
            "LiDAR sensor calculations are vectorized across all rays and obstacles simultaneously.",
            "Benchmark test demonstrates >=3x speedup in environment step throughput.",
            "Output sensor readings remain bitwise identical or within float precision tolerance.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/navigation/navigation2d.py",
            "tests/test_navigation.py",
        ],
        "notes": "Massively speeds up continuous navigation training runs.",
    },
    {
        "num": 53,
        "domain": "Performance & Profiling",
        "milestone": "Phase 20 — Performance & Scaling",
        "labels": ["performance", "planners"],
        "title": "Optimize near-neighbor spatial query in RRT* using KD-tree acceleration",
        "problem": "`RRTStarPlanner` performs linear $O(N)$ brute-force distance searches across all tree nodes for every sample, causing severe slowdown when `max_iterations > 1500`.",
        "current_state": "In `src/adaptive_rl/planners/rrt_star.py:100–120`, `_find_near_nodes()` iterates over the entire node list in pure Python.",
        "proposed_change": "Integrate a KD-tree spatial index (via `scipy.spatial.KDTree` or lightweight 2D quadtree) for nearest-neighbor and radius rewiring queries, achieving $O(\\log N)$ lookup complexity.",
        "scope": "Optimizes neighbor queries in `RRTStarPlanner`.",
        "acceptance_criteria": [
            "Near-neighbor queries execute in $O(\\log N)$ time using spatial indexing.",
            "Planning time on 3000 iterations drops by >=50%.",
            "Path optimality and validity remain completely uncompromised.",
            "Tests in `tests/test_planners.py` verify identical path outputs.",
        ],
        "relevant_files": [
            "src/adaptive_rl/planners/rrt_star.py",
            "tests/test_planners.py",
        ],
        "notes": "Enables scaling RRT* to dense, high-iteration obstacle mazes.",
    },
    {
        "num": 54,
        "domain": "Performance & Profiling",
        "milestone": "Phase 20 — Performance & Scaling",
        "labels": ["performance", "benchmarking"],
        "title": "Add parallel seed execution support to BenchmarkRunner using multiprocessing pool",
        "problem": "`BenchmarkRunner.run()` evaluates seeds sequentially in a single process. Running a 10-seed benchmark takes 10x the single-run duration.",
        "current_state": "In `src/adaptive_rl/benchmarking/__init__.py:339–354`, a standard Python `for seed in self.seeds:` loop executes runs sequentially.",
        "proposed_change": "Introduce `n_jobs: int = 1` in `BenchmarkRunner`. When `n_jobs > 1`, execute independent seed runs across a `concurrent.futures.ProcessPoolExecutor`.",
        "scope": "Modifies `BenchmarkRunner` orchestration loop and CLI `--jobs` option.",
        "acceptance_criteria": [
            "`BenchmarkRunner` accepts `n_jobs: int` parameter.",
            "Parallel seed execution scales near-linearly across CPU cores.",
            "Per-seed logs and artifacts remain cleanly separated without file collisions.",
            "Tests verify parallel execution produces identical aggregate metrics.",
        ],
        "relevant_files": [
            "src/adaptive_rl/benchmarking/__init__.py",
            "src/adaptive_rl/cli.py",
            "tests/test_benchmarking.py",
        ],
        "notes": "Drastically reduces wall-clock time for multi-seed research evaluations.",
    },
    # =========================================================================
    # DOMAIN 15: SECURITY & REPOSITORY HYGIENE (Issues 55 - 57) -> Milestone: Phase 18
    # =========================================================================
    {
        "num": 55,
        "domain": "Security & Repository Hygiene",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["security", "experiments"],
        "title": "Harden YAML configuration loader against arbitrary object instantiation and unsafe paths",
        "problem": "`load_config` parses YAML and constructs filesystem paths without validating against directory traversal or absolute path escapes outside project boundaries.",
        "current_state": "In `src/adaptive_rl/config.py`, `output_dir` and `log_dir` can be configured to arbitrary system paths without boundary checks.",
        "proposed_change": "Add path sanitization and boundary validation in `ExperimentConfig` ensuring output directories do not escape designated workspace roots unless explicitly allowed.",
        "scope": "Hardens `src/adaptive_rl/config.py` path resolution models.",
        "acceptance_criteria": [
            "Path traversal patterns (e.g. `../../etc/`) are rejected with `ConfigError`.",
            "Config loader sanitizes path characters before creating filesystem directories.",
            "Security tests in `tests/test_configuration.py` verify path traversal rejection.",
        ],
        "relevant_files": [
            "src/adaptive_rl/config.py",
            "src/adaptive_rl/experiments/manager.py",
            "tests/test_configuration.py",
        ],
        "notes": "Prevents accidental or malicious filesystem overwrites.",
    },
    {
        "num": 56,
        "domain": "Security & Repository Hygiene",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["security", "ci"],
        "title": "Add automated GitHub secret scanning and dependency vulnerability auditing to CI",
        "problem": "The repository has no automated security scanning to prevent accidental commit of tokens or detect known vulnerabilities in upstream Python packages.",
        "current_state": "No security workflows or dependabot configs exist.",
        "proposed_change": "Add `.github/workflows/security.yml` running `pip-audit` or `trufflehog`/`gitleaks` to detect exposed credentials and vulnerable dependencies.",
        "scope": "Adds CI security workflow.",
        "acceptance_criteria": [
            "CI scans all commits for hardcoded API keys and secrets.",
            "Automated dependency audit checks for known CVEs in transitive packages.",
            "Security alerts flag high-severity vulnerabilities.",
        ],
        "relevant_files": [
            ".github/workflows/security.yml",
            ".github/dependabot.yml",
        ],
        "notes": "Standard open-source supply-chain security practice.",
    },
    {
        "num": 57,
        "domain": "Security & Repository Hygiene",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["security", "provenance"],
        "title": "Validate experiment result file integrity with SHA-256 checksums in ExperimentManifest",
        "problem": "Experiment artifacts (model weights, metrics JSON) can be inadvertently modified, truncated, or overwritten without detection.",
        "current_state": "In `src/adaptive_rl/experiments/manager.py`, `artifact_paths` only stores file paths as strings without cryptographic hashes.",
        "proposed_change": "Compute SHA-256 checksums for generated model weights, metrics, and evaluation reports, storing them in `manifest.artifact_checksums`.",
        "scope": "Adds checksum hashing to `ExperimentManager` post-run artifact finalization.",
        "acceptance_criteria": [
            "`manifest.json` includes SHA-256 checksums for all saved artifacts.",
            "`adaptive-rl experiment inspect --verify` checks file hashes against the manifest.",
            "Detects tampered or corrupted model weights.",
            "Tests verify checksum generation and validation.",
        ],
        "relevant_files": [
            "src/adaptive_rl/experiments/manager.py",
            "src/adaptive_rl/cli.py",
            "tests/test_experiment_manager.py",
        ],
        "notes": "Guarantees cryptographic provenance for published benchmarks.",
    },
    # =========================================================================
    # DOMAIN 16: FUTURE RESEARCH CAPABILITIES (Issues 58 - 62) -> Milestone: Phase 19
    # =========================================================================
    {
        "num": 58,
        "domain": "Future Research Capabilities",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["research", "environments"],
        "title": "Implement domain randomization framework for continuous navigation and drone environments",
        "problem": "Environments currently use fixed physical parameters (friction, mass, drag, sensor noise), limiting sim-to-real robustness studies.",
        "current_state": "Physical parameters are static across episode resets.",
        "proposed_change": "Implement a `DomainRandomizationWrapper` and declarative YAML schema that samples physical parameters (agent mass, friction, LiDAR noise) from uniform or Gaussian distributions on each reset.",
        "scope": "Adds `src/adaptive_rl/environments/wrappers/domain_randomization.py` and configuration support.",
        "acceptance_criteria": [
            "`DomainRandomizationWrapper` perturbs physics and sensor noise per episode.",
            "Parameter distribution bounds are configurable via experiment YAML.",
            "Seeded resets produce reproducible randomized parameter sequences.",
            "Tests verify parameter variation across resets.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/navigation/navigation2d.py",
            "src/adaptive_rl/environments/drone/disturbed_drone.py",
            "src/adaptive_rl/config.py",
            "tests/test_domain_randomization.py",
        ],
        "notes": "Unlocks research into zero-shot policy transfer under physical uncertainty.",
    },
    {
        "num": 59,
        "domain": "Future Research Capabilities",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["research", "evaluation"],
        "title": "Add policy evaluation under controlled environmental distribution shift in GeneralizationEvaluator",
        "problem": "`GeneralizationEvaluator` currently only evaluates disjoint seed partitions; it cannot systematically test policy performance under parameter shift (e.g. testing trained policies on 2x higher wind speeds or obstacle densities).",
        "current_state": "In `src/adaptive_rl/evaluation/generalization.py`, `evaluate_generalization` tests fixed environment kwargs across train and test seeds.",
        "proposed_change": "Extend `GeneralizationDistribution` to support parameter perturbations (e.g. `test_env_kwargs={'max_wind_speed': 8.0}`), calculating distribution-shift transfer gaps.",
        "scope": "Modifies `generalization.py` and adds shift evaluation reporting.",
        "acceptance_criteria": [
            "`GeneralizationDistribution` supports separate parameter dictionaries for test distributions.",
            "Calculates performance degradation specifically attributable to parameter shifts.",
            "Visual summary in dashboard highlights out-of-distribution transfer retention.",
            "Tests verify parameter-shift evaluation.",
        ],
        "relevant_files": [
            "src/adaptive_rl/evaluation/generalization.py",
            "src/adaptive_rl/cli.py",
            "docs/RESEARCH.md",
            "tests/test_generalization.py",
        ],
        "notes": "Enables systematic empirical study of policy out-of-distribution robustness.",
    },
    {
        "num": 60,
        "domain": "Future Research Capabilities",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["research", "benchmarking"],
        "title": "Implement automated policy checkpoint comparison and intermediate performance tracking",
        "problem": "Intermediate policy checkpoints saved during training can only be evaluated manually; there is no automated tool to benchmark the learning curve checkpoints side-by-side to detect policy collapse or catastrophic forgetting.",
        "current_state": "Checkpoints are written to `<output_dir>/checkpoints/` but `BenchmarkRunner` only evaluates the final model.",
        "proposed_change": "Add `adaptive-rl benchmark checkpoints --experiment <id>` command that automatically benchmarks all intermediate checkpoint zip files and plots performance evolution.",
        "scope": "Adds checkpoint evaluation orchestration to `benchmarking/` and CLI.",
        "acceptance_criteria": [
            "Automatically discovers and benchmarks all checkpoints in an experiment directory.",
            "Outputs comparative metrics table and learning trajectory plot.",
            "Identifies highest-performing checkpoint based on validation success rate.",
            "Tests in `tests/test_benchmarking.py` verify checkpoint scanning and evaluation.",
        ],
        "relevant_files": [
            "src/adaptive_rl/benchmarking/__init__.py",
            "src/adaptive_rl/experiments/manager.py",
            "src/adaptive_rl/cli.py",
            "tests/test_benchmarking.py",
        ],
        "notes": "Vital tool for diagnosing training instability and selecting optimal deployment models.",
    },
    {
        "num": 61,
        "domain": "Future Research Capabilities",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["research", "algorithms"],
        "title": "Implement offline trajectory dataset recording and serialization for offline RL baselines",
        "problem": "Trajectories generated by trained policies or planners are discarded. Capturing transition datasets would allow AdaptiveRL to benchmark offline RL algorithms (e.g. Decision Transformer, CQL, IQL).",
        "current_state": "Transitions are stepped through inside Gymnasium environments without an option to buffer and serialize offline datasets.",
        "proposed_change": "Implement an `OfflineDatasetCollector` callback that records `(obs, action, reward, next_obs, done)` tuples to standardized HDF5 or NPZ format.",
        "scope": "Adds dataset collection utilities in `src/adaptive_rl/evaluation/datasets.py`.",
        "acceptance_criteria": [
            "Collector records transitions across multi-episode runs into compressed HDF5/NPZ files.",
            "Dataset includes metadata (environment ID, policy type, total return).",
            "Format is compatible with standard offline RL benchmark loaders.",
            "Tests verify dataset integrity and round-trip loading.",
        ],
        "relevant_files": [
            "src/adaptive_rl/evaluation/evaluator.py",
            "src/adaptive_rl/training/callbacks.py",
            "tests/test_datasets.py",
        ],
        "notes": "Lays groundwork for future offline reinforcement learning research phases.",
    },
    {
        "num": 62,
        "domain": "Future Research Capabilities",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["research", "environments"],
        "title": "Add dynamic obstacle motion prediction feature vector to continuous navigation observation space",
        "problem": "In `ContinuousNavigation2DEnv` and `DisturbedDroneEnv`, observation vectors include instantaneous obstacle coordinates but omit obstacle velocity vectors, forcing agents to infer movement implicitly.",
        "current_state": "In `src/adaptive_rl/environments/drone/disturbed_drone.py:200–250`, observations include static LiDAR and drone velocity, but dynamic obstacle velocities are not exposed.",
        "proposed_change": "Add an optional environment parameter `include_obstacle_velocities: bool = False` that appends relative velocity vectors of moving hazards to the observation vector.",
        "scope": "Modifies observation space computation in `disturbed_drone.py` and `navigation2d.py`.",
        "acceptance_criteria": [
            "`include_obstacle_velocities` adds normalized relative velocity features when enabled.",
            "Observation space dimension updates dynamically and remains within bounds.",
            "Default behavior remains backward-compatible with existing models.",
            "Tests verify observation vector length and values.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/drone/disturbed_drone.py",
            "src/adaptive_rl/environments/navigation/navigation2d.py",
            "tests/test_drone_disturbances.py",
        ],
        "notes": "Enables predictive obstacle avoidance research for autonomous flight.",
    },
]
