"""Data catalog part 2 for issues 21 to 41."""

from typing import Any, Dict, List

ISSUES_DATA_PART2: List[Dict[str, Any]] = [
    # =========================================================================
    # DOMAIN 6: BENCHMARKING & RESEARCH (Issues 21 - 25) -> Milestone: Phase 19
    # =========================================================================
    {
        "num": 21,
        "domain": "Benchmarking & Research",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["benchmarking", "research"],
        "title": "Incorporate hypothesis testing and confidence intervals into multi-seed benchmark comparisons",
        "problem": "`BenchmarkRunner.compare()` calculates only naive arithmetic mean differences and percentage changes across seeds, lacking statistical significance tests.",
        "current_state": "In `src/adaptive_rl/benchmarking/__init__.py:423–436`, `delta = b_stats.mean - a_stats.mean` is computed without calculating p-values or confidence intervals across seeds.",
        "proposed_change": "Incorporate two-sample Welch's t-tests, Mann-Whitney U tests, and stratified bootstrap 95% confidence intervals into `ComparisonReport` and `--compare` CLI output.",
        "scope": "Adds statistical evaluation routines in `benchmarking/` and updates report serialization.",
        "acceptance_criteria": [
            "`ComparisonReport` outputs p-values and 95% bootstrap confidence intervals when seeds >= 3.",
            "CLI comparison table indicates whether performance differences are statistically significant.",
            "Unit tests verify statistical calculations against known distributions.",
        ],
        "relevant_files": [
            "src/adaptive_rl/benchmarking/__init__.py",
            "src/adaptive_rl/cli.py",
            "docs/RESEARCH.md",
            "tests/test_benchmarking.py",
        ],
        "notes": "Aligns AdaptiveRL with statistical standards in reinforcement learning research.",
    },
    {
        "num": 22,
        "domain": "Benchmarking & Research",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["benchmarking", "experiments"],
        "title": "Implement automated ablation matrix generation and execution for curriculum and disturbance parameters",
        "problem": "Running parametric ablation sweeps (e.g. testing 5 obstacle densities or 4 wind intensities) requires manually crafting and launching dozens of YAML configs.",
        "current_state": "The CLI only accepts single config paths or pairwise `--compare`. Parameter grids must be scripted externally.",
        "proposed_change": "Introduce an `adaptive-rl benchmark sweep` command and `AblationMatrixConfig` schema that automatically expands grid parameters, runs multi-seed benchmarks, and outputs an aggregated ablation table.",
        "scope": "Adds ablation sweep orchestration to `benchmarking/` and Typer CLI.",
        "acceptance_criteria": [
            "Ablation sweeps can be defined declaratively in a single YAML matrix configuration.",
            "Sweep runner executes all parameter combinations across specified seeds.",
            "Produces unified comparison matrix CSV and Markdown reports.",
            "Tests in `tests/test_benchmarking.py` verify matrix expansion.",
        ],
        "relevant_files": [
            "src/adaptive_rl/benchmarking/__init__.py",
            "src/adaptive_rl/cli.py",
            "src/adaptive_rl/config.py",
            "tests/test_benchmarking.py",
        ],
        "notes": "Reduces manual effort for scientific ablation studies.",
    },
    {
        "num": 23,
        "domain": "Benchmarking & Research",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["benchmarking", "environments"],
        "title": "Add difficulty-tiered benchmark suites for navigation and drone environments",
        "problem": "Benchmarks currently evaluate arbitrary random seeds without standardized difficulty tiers, preventing apples-to-apples comparisons across papers.",
        "current_state": "`configs/` contains individual environment configs, but lacks standardized 'easy', 'medium', and 'hard' benchmark suite definitions with fixed evaluation seeds.",
        "proposed_change": "Define standardized difficulty tiers (Easy, Medium, Hard) for GridWorld, ContinuousNavigation, and Drone3D based on obstacle density, arena dimensions, and dynamic hazards.",
        "scope": "Adds declarative suite manifests under `configs/benchmarks/` and integration in `adaptive-rl benchmark --suite <name>`.",
        "acceptance_criteria": [
            "Standardized benchmark suites defined for Easy, Medium, and Hard difficulty levels.",
            "Fixed evaluation seed partitions ensure identical evaluation conditions for all users.",
            "CLI allows running full suites via `--suite` option.",
            "Documentation in `docs/RESEARCH.md` details difficulty metrics.",
        ],
        "relevant_files": [
            "configs/benchmarks/navigation_suite.yaml",
            "configs/benchmarks/drone_suite.yaml",
            "src/adaptive_rl/evaluation/scenarios.py",
            "docs/RESEARCH.md",
        ],
        "notes": "Establishes a standardized benchmarking leaderboard.",
    },
    {
        "num": 24,
        "domain": "Benchmarking & Research",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["benchmarking", "cli"],
        "title": "Implement Markdown and LaTeX export formats for benchmark comparison reports",
        "problem": "Researchers must manually copy metrics from terminal tables or JSON files into paper manuscripts and documentation.",
        "current_state": "`ComparisonReport.save()` in `src/adaptive_rl/benchmarking/__init__.py` only supports JSON export.",
        "proposed_change": "Add `to_markdown()` and `to_latex()` export methods to `ComparisonReport`, accessible via CLI flag `--format [json|markdown|latex]`.",
        "scope": "Expands report serialization in `benchmarking/` and adds CLI export options.",
        "acceptance_criteria": [
            "`ComparisonReport.to_markdown()` produces valid GitHub-flavored Markdown comparison tables.",
            "`ComparisonReport.to_latex()` produces clean booktabs LaTeX tables with `\\pm` standard deviations.",
            "CLI flag `--output-format` exports selected format directly.",
            "Tests verify Markdown and LaTeX string formatting.",
        ],
        "relevant_files": [
            "src/adaptive_rl/benchmarking/__init__.py",
            "src/adaptive_rl/cli.py",
            "tests/test_benchmarking.py",
        ],
        "notes": "Significantly accelerates paper writing and technical report preparation.",
    },
    {
        "num": 25,
        "domain": "Benchmarking & Research",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["benchmarking", "research"],
        "title": "Add interquartile mean and stratified bootstrap statistics for robust RL performance aggregation",
        "problem": "Standard arithmetic means are heavily distorted by outlier seed runs. RL research best practices (Agarwal et al., 2021) recommend Interquartile Mean (IQM) and bootstrap confidence bands.",
        "current_state": "`compute_aggregate_stats()` in `src/adaptive_rl/benchmarking/__init__.py:210` only computes mean, std, min, and max.",
        "proposed_change": "Add `iqm: float`, `median: float`, and bootstrap confidence intervals to `AggregateStats`, providing robust statistical estimators resistant to outlier seeds.",
        "scope": "Modifies statistical aggregation functions in `benchmarking/` without breaking existing fields.",
        "acceptance_criteria": [
            "`AggregateStats` computes and stores `iqm` (trimmed mean of middle 50%) and `median`.",
            "NaN handling remains robust across zero or partial failures.",
            "Benchmark reports display IQM alongside mean ± std.",
            "Tests verify IQM and median calculation accuracy.",
        ],
        "relevant_files": [
            "src/adaptive_rl/benchmarking/__init__.py",
            "docs/RESEARCH.md",
            "tests/test_benchmarking.py",
        ],
        "notes": "Elevates publication credibility for empirical studies.",
    },
    # =========================================================================
    # DOMAIN 7: METRICS & EVALUATION (Issues 26 - 29) -> Milestone: Phase 18
    # =========================================================================
    {
        "num": 26,
        "domain": "Metrics & Evaluation",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["metrics", "environments"],
        "title": "Define explicit success semantics and queuing telemetry tracking for TrafficSignalEnv in Evaluator",
        "problem": "`TrafficSignalEnv` never sets `success` or `collision` in `step_info`, causing `Evaluator.evaluate()` to always record a 0.0% success rate and discard queuing telemetry.",
        "current_state": "In `src/adaptive_rl/environments/traffic/intersection.py:268–276`, step info includes queues and departures but neither `success` nor `collision`. In `src/adaptive_rl/evaluation/evaluator.py`, `success_rate` is always 0.",
        "proposed_change": "Set `info['success'] = (not telemetry.overflow)` in `TrafficSignalEnv`, and update `Evaluator` to preserve domain metrics (`mean_queue_length`, `max_wait_time`, `total_departures`) in `additional_metrics`.",
        "scope": "Updates `intersection.py`, `evaluator.py`, and `StandardizedExperimentMetrics`.",
        "acceptance_criteria": [
            "`TrafficSignalEnv` step info contains a boolean `success` indicator.",
            "Non-overflowing traffic episodes yield `success_rate > 0.0`.",
            "Average queue length and throughput are tracked in evaluation reports.",
            "Tests in `tests/test_traffic.py` verify proper evaluation metrics.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/traffic/intersection.py",
            "src/adaptive_rl/evaluation/evaluator.py",
            "src/adaptive_rl/evaluation/metrics.py",
            "tests/test_traffic.py",
        ],
        "notes": "Fixes broken benchmark reporting for traffic signal policies.",
    },
    {
        "num": 27,
        "domain": "Metrics & Evaluation",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["metrics", "architecture"],
        "title": "Enforce strict unavailable-metric semantics across all evaluation reports",
        "problem": "Several evaluation modules silently default unmeasured metrics to 0.0 instead of `None` or `NaN`, misleading users about actual performance.",
        "current_state": "In `EvaluationMetrics` and `StandardizedExperimentMetrics`, fields like `collision_rate` or `planning_time` can default to 0.0 when unmeasured.",
        "proposed_change": "Audit all metric models and ensure all metrics not applicable to a given environment or algorithm default strictly to `None` (JSON `null`).",
        "scope": "Modifies `src/adaptive_rl/evaluation/metrics.py` and factory constructors `from_rl_metrics` and `from_planner_metrics`.",
        "acceptance_criteria": [
            "Unmeasured metrics serialize to JSON `null` rather than `0.0`.",
            "Explicit distinction between zero occurrences (e.g. 0 collisions) and unmeasured metrics.",
            "Tests in `tests/test_standardized_metrics.py` assert `None` semantics.",
        ],
        "relevant_files": [
            "src/adaptive_rl/evaluation/metrics.py",
            "src/adaptive_rl/evaluation/evaluator.py",
            "tests/test_standardized_metrics.py",
        ],
        "notes": "Core philosophical requirement of the AdaptiveRL research platform.",
    },
    {
        "num": 28,
        "domain": "Metrics & Evaluation",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["metrics", "evaluation"],
        "title": "Add per-episode trajectory logging and step-level metric recording to Evaluator",
        "problem": "Evaluator aggregates summary scalars per episode but discards time-series trajectories (positions, actions, velocities), preventing trajectory path analysis.",
        "current_state": "In `src/adaptive_rl/evaluation/evaluator.py:113`, actions, observations, and rewards are stepped through without logging step-by-step histories.",
        "proposed_change": "Introduce `record_trajectories: bool = False` in `Evaluator.evaluate()`. When True, save full episode trajectories to a companion `trajectories.json` file.",
        "scope": "Adds optional trajectory recording in `evaluator.py` without impacting default evaluation performance.",
        "acceptance_criteria": [
            "When `record_trajectories=True`, step-by-step states, actions, and rewards are collected.",
            "Saved trajectories follow a standardized JSON schema.",
            "Default evaluation mode maintains zero overhead.",
            "Tests verify trajectory recording structure.",
        ],
        "relevant_files": [
            "src/adaptive_rl/evaluation/evaluator.py",
            "src/adaptive_rl/config.py",
            "tests/test_evaluation.py",
        ],
        "notes": "Enables visual trajectory plotting and behavior cloning research.",
    },
    {
        "num": 29,
        "domain": "Metrics & Evaluation",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["metrics", "evaluation"],
        "title": "Implement scenario-level breakdown reporting in StandardizedExperimentMetrics",
        "problem": "When evaluating multi-scenario suites, `StandardizedExperimentMetrics` only reports flat global averages, masking individual scenario failure modes.",
        "current_state": "In `src/adaptive_rl/evaluation/evaluator.py:156–170`, `evaluate_scenarios` returns a dictionary of `EvaluationMetrics`, but cannot be cleanly serialized into a unified standardized report.",
        "proposed_change": "Add `per_scenario_metrics: Dict[str, StandardizedExperimentMetrics]` to the standardized metrics model, supporting granular per-scenario inspection.",
        "scope": "Expands `StandardizedExperimentMetrics` and updates `save_report()` serialization.",
        "acceptance_criteria": [
            "`StandardizedExperimentMetrics` supports optional per-scenario sub-reports.",
            "Scenario names, parameters, and individual success rates are preserved in `metrics.json`.",
            "Tests in `tests/test_standardized_metrics.py` verify scenario breakdown persistence.",
        ],
        "relevant_files": [
            "src/adaptive_rl/evaluation/metrics.py",
            "src/adaptive_rl/evaluation/evaluator.py",
            "tests/test_standardized_metrics.py",
        ],
        "notes": "Essential for identifying edge-case failures across diverse test maps.",
    },
    # =========================================================================
    # DOMAIN 8: DASHBOARD & VISUALIZATION (Issues 30 - 33) -> Milestone: Phase 21
    # =========================================================================
    {
        "num": 30,
        "domain": "Dashboard & Visualization",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["dashboard", "robustness"],
        "title": "Handle unreadable manifests and incomplete experiment directories gracefully in Dashboard",
        "problem": "Incomplete experiment folders (e.g. killed/crashed jobs) are silently omitted, and corrupted `manifest.json` files cause `?` and 'unknown' dashboard displays without diagnostics.",
        "current_state": "In `src/adaptive_rl/experiments/manager.py:671–680` and `dashboard.py:105–125`, missing manifests skip the folder entirely, while corrupt manifests fail to show actionable error causes.",
        "proposed_change": "Detect directories missing `manifest.json` but containing `config.yaml`, display them with status `interrupted`, and provide explicit error diagnostics for corrupt JSON files.",
        "scope": "Modifies `ExperimentManager.list_experiments()` and Rich overview rendering in `dashboard.py`.",
        "acceptance_criteria": [
            "Incomplete and interrupted runs are visible in the dashboard overview with distinct styling.",
            "Corrupted manifests show path and parsing error diagnostics.",
            "Tests in `tests/test_dashboard_cli.py` verify handling of empty, partial, and corrupt experiment directories.",
        ],
        "relevant_files": [
            "src/adaptive_rl/experiments/manager.py",
            "src/adaptive_rl/visualization/dashboard.py",
            "tests/test_dashboard_cli.py",
        ],
        "notes": "Prevents user confusion when experiments fail or are terminated prematurely.",
    },
    {
        "num": 31,
        "domain": "Dashboard & Visualization",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["dashboard", "cli"],
        "title": "Add interactive experiment filtering and sorting by environment, algorithm, and date in Dashboard",
        "problem": "The dashboard overview prints an unsorted table of all runs, becoming unmanageable when hundreds of experiments are present.",
        "current_state": "In `src/adaptive_rl/visualization/dashboard.py:71–126`, `render_overview` takes no filter or sort arguments, dumping all runs in chronological order.",
        "proposed_change": "Add CLI options and interactive filter flags to `adaptive-rl dashboard`: `--env`, `--algo`, `--status`, and `--limit`, filtering the Rich overview table dynamically.",
        "scope": "Adds filtering parameters to `dashboard.py` and CLI commands.",
        "acceptance_criteria": [
            "`adaptive-rl dashboard --env navigation --algo sac` displays only matching runs.",
            "`--status [completed|failed|interrupted]` filters by execution status.",
            "`--limit <N>` constrains the overview to the N most recent runs.",
            "Tests in `tests/test_dashboard_cli.py` verify filtering behavior.",
        ],
        "relevant_files": [
            "src/adaptive_rl/visualization/dashboard.py",
            "src/adaptive_rl/cli.py",
            "tests/test_dashboard_cli.py",
        ],
        "notes": "Significantly improves usability for large experiment repositories.",
    },
    {
        "num": 32,
        "domain": "Dashboard & Visualization",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["dashboard"],
        "title": "Add multi-run terminal sparkline trend comparison for reward and episode length distributions",
        "problem": "Terminal sparklines are only rendered for single experiment inspections. Comparing multiple runs lacks comparative distribution visualizations.",
        "current_state": "In `src/adaptive_rl/visualization/dashboard.py:219–260`, `_render_sparkline()` operates only on a single array of values in `render_metrics()`.",
        "proposed_change": "In `render_comparison()`, render comparative distribution blocks and sparklines side-by-side for each compared experiment arm.",
        "scope": "Enhances `render_comparison()` in `dashboard.py` using text-based block characters.",
        "acceptance_criteria": [
            "Comparison view includes aligned text sparklines showing reward spread across runs.",
            "Displays min, median, and max values per arm.",
            "Gracefully handles runs with missing reward arrays.",
            "Tests verify comparative sparkline rendering.",
        ],
        "relevant_files": [
            "src/adaptive_rl/visualization/dashboard.py",
            "tests/test_dashboard_cli.py",
        ],
        "notes": "Pure terminal visualization without external graphical dependencies.",
    },
    {
        "num": 33,
        "domain": "Dashboard & Visualization",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["dashboard", "cli"],
        "title": "Implement exportable Markdown and HTML summary generation from the Dashboard TUI",
        "problem": "Dashboard inspection output cannot be exported directly to shareable documents or static HTML reports for remote viewing.",
        "current_state": "Rich output is written directly to terminal stdout via `Console().print()`. No export functionality exists.",
        "proposed_change": "Use Rich's `console.record = True` and `console.export_html()` / `console.export_text()` to enable `adaptive-rl dashboard --export <path.html|path.md>`.",
        "scope": "Adds export capability to dashboard runner and CLI options.",
        "acceptance_criteria": [
            "`adaptive-rl dashboard --export summary.html` saves a self-contained HTML page.",
            "`adaptive-rl dashboard --export summary.md` exports clean markdown text.",
            "Saved HTML preserves color themes and terminal tables.",
            "Tests verify export file generation.",
        ],
        "relevant_files": [
            "src/adaptive_rl/visualization/dashboard.py",
            "src/adaptive_rl/cli.py",
            "tests/test_dashboard_cli.py",
        ],
        "notes": "Enables sharing experiment dashboards in documentation or PR comments.",
    },
    # =========================================================================
    # DOMAIN 9: CLI & DEVELOPER EXPERIENCE (Issues 34 - 37) -> Milestone: Phase 21
    # =========================================================================
    {
        "num": 34,
        "domain": "CLI & Developer Experience",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["cli", "documentation"],
        "title": "Update adaptive-rl train help text and CLI documentation to accurately reflect PPO and SAC support",
        "problem": "`adaptive-rl train --help` explicitly claims the command is PPO-only, misleading users regarding the platform's full SAC training capabilities.",
        "current_state": "In `src/adaptive_rl/cli.py:437`, the docstring states `Train a reinforcement learning agent using PPO.`, despite calling `get_trainer(config)` which supports SAC.",
        "proposed_change": "Update docstrings, CLI help summaries, and README examples to state multi-algorithm training support (PPO, SAC).",
        "scope": "Modifies `src/adaptive_rl/cli.py` docstrings and documentation references.",
        "acceptance_criteria": [
            "`adaptive-rl --help` lists `train: Train a reinforcement learning agent (PPO, SAC) from config`.",
            "`adaptive-rl train --help` documents algorithm dispatch based on configuration.",
            "Tests in `tests/test_cli.py` verify help message accuracy.",
        ],
        "relevant_files": [
            "src/adaptive_rl/cli.py",
            "README.md",
            "tests/test_cli.py",
        ],
        "notes": "Eliminates documentation contradiction with actual implementation.",
    },
    {
        "num": 35,
        "domain": "CLI & Developer Experience",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["cli"],
        "title": "Add machine-readable --json output flag to experiment inspect and list commands",
        "problem": "CLI experiment inspection commands only print formatted terminal panels, making programmatic parsing in scripts and CI awkward.",
        "current_state": "`adaptive-rl experiment list` and `inspect` output exclusively formatted Rich tables and panels.",
        "proposed_change": "Add `--json` option to `experiment list` and `experiment inspect`, outputting clean, parseable JSON arrays and objects to stdout.",
        "scope": "Modifies CLI command implementations in `src/adaptive_rl/cli.py`.",
        "acceptance_criteria": [
            "`adaptive-rl experiment list --json` outputs a valid JSON list of manifests.",
            "`adaptive-rl experiment inspect <id> --json` outputs complete manifest and metrics JSON.",
            "Formatting errors or colors are suppressed when `--json` is active.",
            "Tests in `tests/test_cli.py` parse JSON CLI output.",
        ],
        "relevant_files": [
            "src/adaptive_rl/cli.py",
            "tests/test_cli.py",
        ],
        "notes": "Enables integration with jq, bash pipelines, and automated reporting.",
    },
    {
        "num": 36,
        "domain": "CLI & Developer Experience",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["cli", "architecture"],
        "title": "Implement dry-run configuration validation command with environment parameter pre-flight checks",
        "problem": "`adaptive-rl config validate` only verifies YAML syntax against Pydantic models; it does not instantiate environments to check if keyword arguments are valid.",
        "current_state": "In `src/adaptive_rl/cli.py`, `config validate` calls `load_config(path)` but never tests if `make_env(config.environment.name, **config.environment.parameters)` succeeds.",
        "proposed_change": "Enhance `config validate` with a `--preflight` or `--dry-run` flag that validates environment constructor parameters, algorithm compatibility, and directory write permissions.",
        "scope": "Expands config validation command in `cli.py`.",
        "acceptance_criteria": [
            "`adaptive-rl config validate --preflight` checks environment instantiation without running training.",
            "Catches invalid environment parameters before starting compute-heavy jobs.",
            "Clear exit codes (0 = valid, 1 = invalid).",
            "Tests verify detection of invalid environment kwargs.",
        ],
        "relevant_files": [
            "src/adaptive_rl/cli.py",
            "src/adaptive_rl/config.py",
            "tests/test_cli.py",
        ],
        "notes": "Prevents failed training runs due to typoed environment parameters.",
    },
    {
        "num": 37,
        "domain": "CLI & Developer Experience",
        "milestone": "Phase 21 — Developer Experience",
        "labels": ["cli", "documentation"],
        "title": "Add shell auto-completion installation command for bash, zsh, and fish shells",
        "problem": "While Typer supports shell autocompletion natively, AdaptiveRL does not document or provide a dedicated command to install shell completion scripts.",
        "current_state": "Users must manually discover Typer's hidden `--install-completion` arguments.",
        "proposed_change": "Add an explicit `adaptive-rl completion install` and `adaptive-rl completion show` command with documentation in `README.md`.",
        "scope": "Adds completion commands to Typer app in `cli.py`.",
        "acceptance_criteria": [
            "`adaptive-rl completion --help` provides clear instructions for bash, zsh, and fish.",
            "Subcommands and registered environments/algorithms autocomplete in the shell.",
            "Documentation updated in `README.md`.",
        ],
        "relevant_files": [
            "src/adaptive_rl/cli.py",
            "README.md",
        ],
        "notes": "Polishes developer ergonomics for terminal users.",
    },
    # =========================================================================
    # DOMAIN 10: TESTING & QUALITY (Issues 38 - 41) -> Milestone: Phase 18
    # =========================================================================
    {
        "num": 38,
        "domain": "Testing & Quality",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["testing"],
        "title": "Fix untyped test fixtures in test_algorithm_registry to enforce zero-error mypy checks",
        "problem": "Running `uv run mypy tests/` fails with `error: Function is missing a type annotation [no-untyped-def]` in `tests/test_algorithm_registry.py:31`.",
        "current_state": "`def _dummy_factory(self, **kwargs)` has no type annotations, violating `pyproject.toml`'s `disallow_untyped_defs = true` setting.",
        "proposed_change": "Add full type annotations to test helpers in `tests/test_algorithm_registry.py` and verify that `mypy tests/` completes with 0 errors.",
        "scope": "Modifies test fixture signatures in `tests/test_algorithm_registry.py`.",
        "acceptance_criteria": [
            "`_dummy_factory` and all test methods in `test_algorithm_registry.py` are strictly typed.",
            "`uv run mypy tests/` exits with code 0 across all 20 test files.",
        ],
        "relevant_files": [
            "tests/test_algorithm_registry.py",
            "pyproject.toml",
        ],
        "notes": "Enables strict mypy checking across the entire repository in CI.",
    },
    {
        "num": 39,
        "domain": "Testing & Quality",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["testing", "environments"],
        "title": "Implement Farama Gymnasium check_env conformance test suite across all environments",
        "problem": "Several environments are tested only through basic instantiation or wrapped instances, triggering wrapper warnings during `check_env`.",
        "current_state": "In `tests/test_curriculum.py`, `check_env` warns about wrapped environments. In several tests, unwrapped environments are not tested against alternative render modes.",
        "proposed_change": "Add a dedicated `tests/test_gymnasium_conformance.py` suite that systematically runs `check_env(env.unwrapped)` on all registered environments across all supported render modes.",
        "scope": "Adds a unified conformance test file covering all 5 core environments.",
        "acceptance_criteria": [
            "All environments pass `check_env` with zero warnings.",
            "All declared render modes (`ansi`, `human`, `rgb_array`) are tested for each environment.",
            "Observation space bounds and dtype consistency are validated.",
        ],
        "relevant_files": [
            "tests/test_gymnasium_conformance.py",
            "src/adaptive_rl/environments/registry.py",
            "tests/test_curriculum.py",
        ],
        "notes": "Guarantees 100% Farama Gymnasium compliance.",
    },
    {
        "num": 40,
        "domain": "Testing & Quality",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["testing", "environments"],
        "title": "Add property-based testing for procedural GridWorld layout solvability using hypothesis",
        "problem": "Random seeds in `GridWorldGenerator` can theoretically generate disconnected start/goal partitions when obstacle density is high. No property tests verify solvability guarantees.",
        "current_state": "Existing tests in `tests/test_gridworld.py` test a few fixed seeds (42, 100).",
        "proposed_change": "Introduce property-based tests using `hypothesis` that generate hundreds of random grid dimensions and obstacle counts, verifying that `AStarPlanner` always finds a valid path when start and goal are in the same connected component.",
        "scope": "Adds property tests in `tests/test_gridworld_properties.py`.",
        "acceptance_criteria": [
            "Property test verifies grid boundary invariance and agent coordinate bounds.",
            "Validates that obstacle-free components remain connected.",
            "Integrates into regular pytest test runs.",
        ],
        "relevant_files": [
            "tests/test_gridworld_properties.py",
            "src/adaptive_rl/environments/gridworld/generator.py",
            "tests/test_gridworld.py",
        ],
        "notes": "Eliminates edge-case generation bugs.",
    },
    {
        "num": 41,
        "domain": "Testing & Quality",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["testing", "experiments"],
        "title": "Add end-to-end regression test for full experiment lifecycle from YAML to dashboard inspection",
        "problem": "Unit tests test `ExperimentManager`, CLI commands, and dashboard rendering in isolation, but no automated integration test runs the full pipeline end-to-end in a clean directory.",
        "current_state": "Tests mock various parts of the filesystem or trainer execution.",
        "proposed_change": "Add `tests/test_e2e_lifecycle.py` that runs a 100-step training job from a real YAML config into a `tmp_path`, verifies artifact creation (`model/`, `manifest.json`, `metrics.json`), and executes `adaptive-rl dashboard --experiment <id>` on the result.",
        "scope": "Adds an end-to-end smoke test verifying full component integration.",
        "acceptance_criteria": [
            "Full experiment pipeline executes cleanly in a temporary test directory.",
            "All expected artifacts (`manifest.json`, `metrics.json`, `config.yaml`) are verified on disk.",
            "Dashboard and CLI inspect commands successfully read generated artifacts.",
            "Runs in under 5 seconds as a standard pytest test.",
        ],
        "relevant_files": [
            "tests/test_e2e_lifecycle.py",
            "src/adaptive_rl/experiments/manager.py",
            "src/adaptive_rl/cli.py",
            "src/adaptive_rl/visualization/dashboard.py",
        ],
        "notes": "Critical integration test preventing end-to-end user-facing regressions.",
    },
]
