"""Data catalog for the 62-issue engineering roadmap of AdaptiveRL."""

from typing import Any, Dict, List

ISSUES_DATA: List[Dict[str, Any]] = [
    # =========================================================================
    # DOMAIN 1: CORE ARCHITECTURE (Issues 1 - 4) -> Milestone: Phase 18
    # =========================================================================
    {
        "num": 1,
        "domain": "Core Architecture",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["architecture", "planners"],
        "title": "Standardize public abstract interface for classical and learning-based planners",
        "problem": "The abstract class `BasePlanner` is currently coupled to 2D discrete grid coordinates (col, row), preventing continuous and 3D planners from inheriting from it.",
        "current_state": "In `src/adaptive_rl/planners/base.py`, `BasePlanner.plan()` strictly accepts integer grid bounds and coordinates. Consequently, `RRTStarPlanner` in `src/adaptive_rl/planners/rrt_star.py` cannot inherit from `BasePlanner`, forcing `PlannerAdapter` (`src/adaptive_rl/planners/adapter.py`) to maintain disparate `isinstance` branches.",
        "proposed_change": "Introduce a generic, coordinate-agnostic `BasePlanner[CoordT, ObstacleT]` interface or clean discrete/continuous subclass hierarchy that establishes uniform method signatures for planning, validation, and metadata queries.",
        "scope": "Covers planner base classes, adapter dispatch, and type signatures. Does not alter underlying A* or RRT* search algorithms.",
        "acceptance_criteria": [
            "A unified planner interface is established in `src/adaptive_rl/planners/base.py`.",
            "`RRTStarPlanner` inherits from the generalized base planner interface.",
            "`PlannerAdapter` dispatches via interface polymorphism without concrete type-switching.",
            "Existing unit tests in `tests/test_planners.py` pass without regression.",
        ],
        "relevant_files": [
            "src/adaptive_rl/planners/base.py",
            "src/adaptive_rl/planners/rrt_star.py",
            "src/adaptive_rl/planners/adapter.py",
            "tests/test_planners.py",
        ],
        "notes": "Foundation for classical 3D planning baselines.",
    },
    {
        "num": 2,
        "domain": "Core Architecture",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["architecture", "environments", "algorithms"],
        "title": "Introduce explicit environment capability metadata for observation and action space requirements",
        "problem": "Algorithms fail dynamically at runtime if paired with incompatible environments (e.g. SAC paired with discrete action GridWorld) without early pre-flight validation.",
        "current_state": "In `src/adaptive_rl/algorithms/registry.py` and `src/adaptive_rl/environments/registry.py`, metadata records action spaces as simple strings ('discrete', 'continuous') without formal validation against algorithm constraints prior to environment instantiation.",
        "proposed_change": "Implement a declarative capability matching mechanism (`validate_compatibility(algo_name, env_name)`) that checks action space types, observation dimensionality, and reward requirements during configuration loading.",
        "scope": "Covers registry metadata schemas, configuration pre-validation, and user-facing error reporting.",
        "acceptance_criteria": [
            "`AlgorithmRegistry` and `EnvironmentRegistry` expose formal compatibility validation methods.",
            "`load_config()` or `ExperimentManager` validates compatibility before allocating resources.",
            "Descriptive error messages are raised when attempting to run incompatible pairs (e.g. SAC on GridWorld).",
            "Tests added in `tests/test_algorithm_registry.py` covering positive and negative compatibility checks.",
        ],
        "relevant_files": [
            "src/adaptive_rl/algorithms/registry.py",
            "src/adaptive_rl/environments/registry.py",
            "src/adaptive_rl/config.py",
            "tests/test_algorithm_registry.py",
        ],
        "notes": "Improves developer UX and prevents wasted compute.",
    },
    {
        "num": 3,
        "domain": "Core Architecture",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["architecture", "cli"],
        "title": "Enforce strict import boundaries and decouple training engines from CLI presentation layer",
        "problem": "CLI modules and training engine callbacks exhibit bidirectional dependencies, where core training routines import Rich console utilities.",
        "current_state": "In `src/adaptive_rl/cli.py` and callbacks under `src/adaptive_rl/curriculum/`, presentation components and Rich formatting panels are imported directly inside execution loops, hindering headless or programmatic usage.",
        "proposed_change": "Establish strict layer separation: core training and evaluation packages must emit pure events or telemetry objects; CLI/TUI layers consume these via callbacks or listeners.",
        "scope": "Refactors callback interfaces and CLI hooks to eliminate presentation library imports inside `src/adaptive_rl/training/`.",
        "acceptance_criteria": [
            "`src/adaptive_rl/training/` and `src/adaptive_rl/curriculum/` have zero imports from `rich` or `typer`.",
            "A clean event/callback protocol allows CLI to attach custom progress renderers.",
            "Headless training runs without initializing terminal consoles.",
            "Tests verify clean import boundaries and mock progress consumers.",
        ],
        "relevant_files": [
            "src/adaptive_rl/cli.py",
            "src/adaptive_rl/training/base.py",
            "src/adaptive_rl/curriculum/callbacks.py",
            "tests/test_imports.py",
        ],
        "notes": "Improves modularity for third-party library consumption.",
    },
    {
        "num": 4,
        "domain": "Core Architecture",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["architecture", "testing"],
        "title": "Introduce public API freeze tests and export manifest verification for adaptive_rl package",
        "problem": "The top-level `adaptive_rl` namespace has no regression tests enforcing public export stability, risking inadvertent breaking changes during internal module refactors.",
        "current_state": "`src/adaptive_rl/__init__.py` exports symbols such as `make_env`, `load_config`, and `Evaluator`, but no automated test checks `__all__` completeness or backward compatibility.",
        "proposed_change": "Add an API contract test suite in `tests/test_api_freeze.py` that asserts all documented public classes, functions, and exceptions remain importable with unchanged signatures.",
        "scope": "Adds automated testing for top-level exports and public module surfaces without altering internal code.",
        "acceptance_criteria": [
            "`tests/test_api_freeze.py` verifies all members of `__all__` across core modules.",
            "Public function signatures are tested against signature drift.",
            "CI catches accidental deletion or renaming of public symbols.",
        ],
        "relevant_files": [
            "src/adaptive_rl/__init__.py",
            "tests/test_api_freeze.py",
            "tests/test_imports.py",
        ],
        "notes": "Ensures semantic versioning guarantees for external consumers.",
    },
    # =========================================================================
    # DOMAIN 2: ENVIRONMENT ENGINEERING (Issues 5 - 8) -> Milestone: Phase 22
    # =========================================================================
    {
        "num": 5,
        "domain": "Environment Engineering",
        "milestone": "Phase 22 — Release Engineering",
        "labels": ["environments"],
        "title": "Register AdaptiveRL environments with Farama Gymnasium global registry to eliminate spec warnings",
        "problem": "Custom environments are instantiated via local factories rather than Farama Gymnasium's global registry, causing 9 spec warnings during `check_env` and preventing `gymnasium.make` usage.",
        "current_state": "In `src/adaptive_rl/environments/registry.py`, environments are registered internally in `EnvironmentRegistry`. Farama Gymnasium's `gym.envs.registration.register()` is not called.",
        "proposed_change": "Register standard environment IDs (`AdaptiveRL/GridWorld-v0`, `AdaptiveRL/Navigation2D-v0`, `AdaptiveRL/Drone3D-v0`, `AdaptiveRL/Traffic-v0`) using Gymnasium's registration entry points.",
        "scope": "Updates environment registration module and adds standard Gymnasium entry points in `pyproject.toml`.",
        "acceptance_criteria": [
            "All AdaptiveRL environments can be instantiated via `gymnasium.make('AdaptiveRL/<EnvId>')`.",
            "`gymnasium.utils.env_checker.check_env` passes on all environments with zero warnings.",
            "Default observation and action space specs are registered.",
            "Tests in `tests/test_registry.py` verify standard `gymnasium.make` integration.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/registry.py",
            "src/adaptive_rl/environments/__init__.py",
            "tests/test_registry.py",
        ],
        "notes": "Enables seamless integration with SB3, CleanRL, and external benchmarks.",
    },
    {
        "num": 6,
        "domain": "Environment Engineering",
        "milestone": "Phase 22 — Release Engineering",
        "labels": ["environments", "reproducibility"],
        "title": "Add deterministic scenario replay and serialization for procedural GridWorld and ContinuousNavigation environments",
        "problem": "Procedurally generated obstacle maps can only be replayed via seed numbers; there is no format to export specific failure layouts as standalone scenario files for visual debugging.",
        "current_state": "`GridWorldGenerator` and `ContinuousNavigation2DEnv` generate obstacles randomly on reset. Scenarios in `src/adaptive_rl/evaluation/scenarios.py` specify static presets but cannot serialize active episodes.",
        "proposed_change": "Implement `export_scenario(filepath)` and `load_scenario(filepath)` in environment classes to save and restore exact agent start, goal, and obstacle configurations to JSON/YAML.",
        "scope": "Covers GridWorld and ContinuousNavigation2D serialization. Drone environment serialization covered in subsequent issue.",
        "acceptance_criteria": [
            "Environments can serialize their active layout to a standardized JSON scenario file.",
            "Serialized scenario files can be reloaded via `env.reset(options={'scenario_file': path})`.",
            "Path planners and agents execute identically on reloaded scenarios.",
            "Unit tests in `tests/test_scenarios.py` verify exact round-trip serialization.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/gridworld/generator.py",
            "src/adaptive_rl/environments/navigation/generator.py",
            "src/adaptive_rl/evaluation/scenarios.py",
            "tests/test_scenarios.py",
        ],
        "notes": "Essential for regression testing hard-to-solve environment seeds.",
    },
    {
        "num": 7,
        "domain": "Environment Engineering",
        "milestone": "Phase 20 — Performance & Scaling",
        "labels": ["environments", "performance"],
        "title": "Implement vectorized environment wrapper support for parallel trajectory collection",
        "problem": "Training and evaluation currently step through single environment instances sequentially, bottlenecking GPU utilization during RL policy updates.",
        "current_state": "In `src/adaptive_rl/training/ppo.py` and `src/adaptive_rl/training/sac.py`, trainers wrap environments in a standard single-process Gymnasium instance.",
        "proposed_change": "Introduce integration with `gymnasium.vector.AsyncVectorEnv` and `SyncVectorEnv`, enabling multi-environment parallel rollout collection configurable via `training.num_envs`.",
        "scope": "Adds vectorized environment factory utilities and updates PPO trainer to handle vectorized observations.",
        "acceptance_criteria": [
            "`make_env` or dedicated `make_vec_env` supports `num_envs: int` parameter.",
            "`PPOTrainer` correctly ingests batched step transitions when `num_envs > 1`.",
            "Deterministic per-sub-environment seeding prevents synchronized duplicate trajectories.",
            "Benchmark test demonstrates >=2x speedup on multi-core CPU.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/registry.py",
            "src/adaptive_rl/training/ppo.py",
            "src/adaptive_rl/config.py",
            "tests/test_training.py",
        ],
        "notes": "Significantly accelerates large-scale training runs.",
    },
    {
        "num": 8,
        "domain": "Environment Engineering",
        "milestone": "Phase 22 — Release Engineering",
        "labels": ["environments"],
        "title": "Add configurable obstacle density distributions and dynamic speed scaling in Drone3DEnv",
        "problem": "In `DisturbedDroneEnv`, dynamic obstacle counts and speeds are hardcoded, limiting scenario diversity and curriculum progression.",
        "current_state": "In `src/adaptive_rl/environments/drone/disturbed_drone.py`, dynamic obstacles are generated with fixed velocity ranges and static clearance radiuses.",
        "proposed_change": "Expose `dynamic_obstacle_speed_range: Tuple[float, float]`, `obstacle_density_distribution: str`, and `moving_obstacle_behavior: str` as configurable environment parameters.",
        "scope": "Modifies `DisturbedDroneEnv` and `dynamic_obstacles.py` parameter parsing without changing kinematic physics.",
        "acceptance_criteria": [
            "Dynamic obstacle speeds and densities can be configured via YAML.",
            "New presets for 'calm', 'moderate', and 'storm' disturbance profiles.",
            "Tests verify obstacle count and speed distribution match configuration.",
        ],
        "relevant_files": [
            "src/adaptive_rl/environments/drone/disturbed_drone.py",
            "src/adaptive_rl/environments/drone/dynamic_obstacles.py",
            "tests/test_drone_disturbances.py",
        ],
        "notes": "Enhances robustness benchmarking against dynamic hazards.",
    },
    # =========================================================================
    # DOMAIN 3: RL ALGORITHMS (Issues 9 - 12) -> Milestone: Phase 18
    # =========================================================================
    {
        "num": 9,
        "domain": "RL Algorithms",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["algorithms", "experiments"],
        "title": "Implement resumable training from saved checkpoints for PPO and SAC algorithms",
        "problem": "Training runs interrupted by crashes, timeouts, or compute preemption cannot resume from existing checkpoint zip files.",
        "current_state": "In `src/adaptive_rl/training/ppo.py` and `sac.py`, trainers save checkpoints at `checkpoint_freq` intervals, but only expose `fit()` from step 0. Resuming from step N is not supported.",
        "proposed_change": "Add `resume_from_checkpoint: Path` parameter to `TrainingConfig` and trainer classes, restoring model weights, optimizer states, and cumulative timestep counters.",
        "scope": "Applies to `PPOTrainer` and `SACTrainer`. Ensures tensorboard and curriculum state correctly resume.",
        "acceptance_criteria": [
            "`adaptive-rl train --resume <checkpoint_path>` seamlessly continues training.",
            "Total timesteps and replay buffer state (for SAC) are accurately restored.",
            "Verification test proves training 10k + 10k steps produces equivalent learning curves to 20k uninterrupted steps.",
        ],
        "relevant_files": [
            "src/adaptive_rl/training/base.py",
            "src/adaptive_rl/training/ppo.py",
            "src/adaptive_rl/training/sac.py",
            "src/adaptive_rl/cli.py",
            "tests/test_training.py",
        ],
        "notes": "Critical for long-running drone and curriculum experiments.",
    },
    {
        "num": 10,
        "domain": "RL Algorithms",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["algorithms", "provenance"],
        "title": "Add structured policy metadata and training provenance to saved model zip artifacts",
        "problem": "Model `.zip` files produced by Stable-Baselines3 contain PyTorch weights but lack embedded AdaptiveRL provenance metadata (git commit, exact hyperparameters, observation space bounds).",
        "current_state": "Model weights are saved directly via `model.save(filepath)`. The only metadata resides externally in `manifest.json`.",
        "proposed_change": "Embed a structured `policy_metadata.json` file inside the model zip archive (or companion `.meta.json`) containing algorithm version, training seed, environment ID, and normalized observation statistics.",
        "scope": "Updates model export/import helpers in `BaseAlgorithm` and `training/base.py`.",
        "acceptance_criteria": [
            "Saved model archives contain an embedded metadata descriptor.",
            "`BaseAlgorithm.from_pretrained()` inspects and verifies metadata compatibility before loading weights.",
            "Mismatched observation or action space dimensions fail fast with clear errors.",
            "Tests in `tests/test_ppo.py` verify metadata persistence.",
        ],
        "relevant_files": [
            "src/adaptive_rl/algorithms/base.py",
            "src/adaptive_rl/training/base.py",
            "tests/test_ppo.py",
        ],
        "notes": "Prevents loading models into incompatible environments during evaluation.",
    },
    {
        "num": 11,
        "domain": "RL Algorithms",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["algorithms", "performance"],
        "title": "Add configurable device selection and mixed-precision execution for SB3 algorithm adapters",
        "problem": "Device selection is implicitly unconfigured, defaulting to PyTorch fallback without explicit YAML control for `cpu`, `cuda`, or `mps`.",
        "current_state": "In `src/adaptive_rl/algorithms/ppo.py` and `sac.py`, `device='auto'` is passed to SB3 constructors without exposing hardware device controls in `AlgorithmConfig`.",
        "proposed_change": "Add `device: Literal['auto', 'cpu', 'cuda', 'mps'] = 'auto'` to algorithm schemas, validating hardware availability and logging selected compute device.",
        "scope": "Updates configuration schemas and algorithm initialization parameters.",
        "acceptance_criteria": [
            "`device` parameter is configurable via experiment YAML files.",
            "Selecting an unavailable device (e.g. `cuda` on CPU machine) raises an informative error.",
            "Algorithm metadata records the actual execution device in `manifest.json`.",
            "Tests verify device resolution logic.",
        ],
        "relevant_files": [
            "src/adaptive_rl/config.py",
            "src/adaptive_rl/algorithms/ppo.py",
            "src/adaptive_rl/algorithms/sac.py",
            "tests/test_configuration.py",
        ],
        "notes": "Essential for reproducible GPU cluster execution.",
    },
    {
        "num": 12,
        "domain": "RL Algorithms",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["algorithms", "architecture"],
        "title": "Standardize training callback pipeline across flat, curriculum, and disturbance training loops",
        "problem": "Curriculum learning and standard training maintain divergent callback architectures, creating duplicate checkpointing logic and logging inconsistencies.",
        "current_state": "`TrainingCallback` in `src/adaptive_rl/training/callbacks.py` and `CurriculumCallback` in `src/adaptive_rl/curriculum/callbacks.py` implement overlapping metric logging, checkpoint saving, and evaluation triggering.",
        "proposed_change": "Consolidate callback interfaces into a unified `AdaptiveRLCallback` base class with lifecycle hooks: `on_step()`, `on_episode_end()`, `on_stage_advance()`, `on_checkpoint()`.",
        "scope": "Refactors callback classes across `training/` and `curriculum/` packages.",
        "acceptance_criteria": [
            "A unified callback lifecycle interface is shared across all training modalities.",
            "Checkpointing behavior is strictly consistent regardless of whether curriculum learning is enabled.",
            "Metric logging formats match between standard and curriculum training.",
            "Tests in `tests/test_curriculum.py` verify callback hook invocation.",
        ],
        "relevant_files": [
            "src/adaptive_rl/training/callbacks.py",
            "src/adaptive_rl/curriculum/callbacks.py",
            "src/adaptive_rl/training/base.py",
            "tests/test_curriculum.py",
        ],
        "notes": "Eliminates duplicate logic and simplifies callback extensions.",
    },
    # =========================================================================
    # DOMAIN 4: CLASSICAL PLANNERS (Issues 13 - 16) -> Milestone: Phase 19
    # =========================================================================
    {
        "num": 13,
        "domain": "Classical Planners",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["planners", "metrics"],
        "title": "Eliminate 0.0 path length encoding for failed planner episodes in PlannerAdapter",
        "problem": "In `PlannerAdapter`, failed search episodes record `0.0` in `all_path_lengths`, contaminating raw trajectory data and creating misleading 0-length entries in metric dumps.",
        "current_state": "In `src/adaptive_rl/planners/adapter.py:208` and line 284, `else: path_lengths.append(0.0)` is executed when path search fails to find a valid route.",
        "proposed_change": "Represent failed search episodes as `None` or `float('nan')` in `all_path_lengths`, conforming to the project's rule that unobtained metrics are never encoded as zero.",
        "scope": "Updates `PlannerAdapter` and `PlannerEvaluationMetrics.all_path_lengths` type definitions.",
        "acceptance_criteria": [
            "`all_path_lengths` stores `None` for failed search episodes.",
            "`mean_path_length` and `std_path_length` calculations remain strictly over successful episodes.",
            "JSON serialization exports `null` for failed entries.",
            "Unit tests in `tests/test_planners.py` verify proper representation of failed episodes.",
        ],
        "relevant_files": [
            "src/adaptive_rl/planners/adapter.py",
            "src/adaptive_rl/evaluation/metrics.py",
            "tests/test_planners.py",
        ],
        "notes": "Ensures statistical validity in planner comparison studies.",
    },
    {
        "num": 14,
        "domain": "Classical Planners",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["planners", "performance"],
        "title": "Implement path smoothing and shortcutting post-processor for RRT* trajectories",
        "problem": "RRT* paths in continuous 2D space suffer from piecewise-linear waypoint chatter, resulting in unnatural zig-zag trajectories and suboptimal arc lengths.",
        "current_state": "In `src/adaptive_rl/planners/rrt_star.py`, the path is extracted directly by traversing parent node pointers without post-processing.",
        "proposed_change": "Implement an optional path smoothing post-processor (raycast shortcutting and B-spline interpolation) that reduces waypoint count and trajectory length while preserving collision clearance.",
        "scope": "Adds a post-processing method to `RRTStarPlanner` enabled via configuration parameter `smooth_path: bool = True`.",
        "acceptance_criteria": [
            "Path shortcutting validates obstacle clearance before connecting non-adjacent waypoints.",
            "Smoothed paths have equal or shorter Euclidean length than raw RRT* paths.",
            "Zero obstacle collisions are introduced by smoothing.",
            "Unit tests compare smoothed vs raw path metrics.",
        ],
        "relevant_files": [
            "src/adaptive_rl/planners/rrt_star.py",
            "src/adaptive_rl/config.py",
            "tests/test_planners.py",
        ],
        "notes": "Produces realistic navigation baselines for continuous environments.",
    },
    {
        "num": 15,
        "domain": "Classical Planners",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["planners", "reproducibility"],
        "title": "Add configurable search timeout and node expansion limits to A* and RRT* planners",
        "problem": "Planners only support fixed iteration counts. In complex or unsolvable obstacle configurations, planners can stall benchmarks indefinitely without wall-clock timeouts.",
        "current_state": "`AStarPlanner` and `RRTStarPlanner` loop until the iteration budget expires or open sets empty, without tracking elapsed wall-clock seconds during the search loop.",
        "proposed_change": "Introduce `timeout_seconds: Optional[float] = None` in planner parameters. If elapsed time exceeds timeout, terminate search and return `PlannerResult(success=False, failure_reason='timeout')`.",
        "scope": "Modifies search loops in `astar.py` and `rrt_star.py` to check elapsed time periodically.",
        "acceptance_criteria": [
            "Planners respect `timeout_seconds` configuration parameter.",
            "When timed out, `PlannerResult` clearly records 'timeout' failure reason.",
            "Benchmark runner cleanly handles timed-out planner episodes.",
            "Tests verify timeout triggering on adversarial maps.",
        ],
        "relevant_files": [
            "src/adaptive_rl/planners/astar.py",
            "src/adaptive_rl/planners/rrt_star.py",
            "src/adaptive_rl/config.py",
            "tests/test_planners.py",
        ],
        "notes": "Guarantees predictable execution times during automated benchmarking.",
    },
    {
        "num": 16,
        "domain": "Classical Planners",
        "milestone": "Phase 19 — Benchmarking & Research",
        "labels": ["planners", "research"],
        "title": "Implement classical 3D kinodynamic planning baseline for Drone3D navigation",
        "problem": "The platform provides classical baselines for 2D GridWorld (A*) and 2D Navigation (RRT*), but lacks any classical planning baseline for `Drone3DEnv`, preventing RL vs planner comparisons in 3D.",
        "current_state": "As documented in `docs/RESEARCH.md`, 3D drone planning baselines are currently absent. `PlannerAdapter` rejects 3D drone environments.",
        "proposed_change": "Implement a 3D RRT* motion planner (`RRTStar3DPlanner`) navigating 3D spherical and cylindrical obstacle fields, with adapter support in `PlannerAdapter`.",
        "scope": "Adds `src/adaptive_rl/planners/rrt_star_3d.py` and updates `PlannerAdapter` to evaluate 3D drone environments.",
        "acceptance_criteria": [
            "`RRTStar3DPlanner` plans 3D collision-free trajectories between `(x, y, z)` endpoints.",
            "Validates obstacle clearance against 3D spherical obstacles in `Drone3DEnv`.",
            "`PlannerAdapter` can evaluate `RRTStar3DPlanner` on `Drone3DEnv`.",
            "Benchmark reports compare 3D PPO/SAC policies against 3D RRT* baseline.",
        ],
        "relevant_files": [
            "src/adaptive_rl/planners/rrt_star.py",
            "src/adaptive_rl/planners/adapter.py",
            "docs/RESEARCH.md",
            "tests/test_planners.py",
        ],
        "notes": "Fulfills a key methodological goal outlined in the project research vision.",
    },
    # =========================================================================
    # DOMAIN 5: EXPERIMENT MANAGEMENT (Issues 17 - 20) -> Milestone: Phase 18
    # =========================================================================
    {
        "num": 17,
        "domain": "Experiment Management",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["experiments", "reproducibility"],
        "title": "Synchronize evaluation seed generation between RL policies and classical planners",
        "problem": "RL evaluation uses `seed + 10000` while classical planners use `seed`. When benchmarking RL vs A*/RRT* under the same seed, they evaluate on different procedural map layouts.",
        "current_state": "In `src/adaptive_rl/experiments/manager.py:413` (RL) `base_seed = config.seed + 10000`, while in line 517 (planners) `base_seed = config.seed`.",
        "proposed_change": "Harmonize evaluation seed assignment: introduce an explicit `eval_seed_offset: int = 10000` in `EvaluationConfig`, ensuring both RL policies and planners evaluate on identical episode instances.",
        "scope": "Modifies `manager.py` and `config.py` evaluation seed resolution.",
        "acceptance_criteria": [
            "RL algorithms and classical planners evaluate on identical seed sequences when configured with the same seed.",
            "Comparative benchmark reports test both paradigms on identical maps.",
            "Tests in `tests/test_experiment_manager.py` assert seed parity.",
        ],
        "relevant_files": [
            "src/adaptive_rl/experiments/manager.py",
            "src/adaptive_rl/config.py",
            "src/adaptive_rl/benchmarking/__init__.py",
            "tests/test_experiment_manager.py",
        ],
        "notes": "Essential for scientific rigor in baseline comparisons.",
    },
    {
        "num": 18,
        "domain": "Experiment Management",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["experiments", "architecture"],
        "title": "Implement schema versioning and migration utilities for ExperimentManifest artifacts",
        "problem": "`manifest.json` files lack a schema version identifier, risking deserialization errors or silent corruption as new metadata fields are introduced.",
        "current_state": "In `src/adaptive_rl/experiments/manager.py`, `ExperimentManifest` is serialized directly via `asdict()` without a `schema_version` attribute.",
        "proposed_change": "Add `schema_version: str = '1.0.0'` to `ExperimentManifest`. Implement a schema migration utility in `manager.py` that upgrades older manifest files upon inspection.",
        "scope": "Updates `ExperimentManifest` dataclass and manifest loading methods.",
        "acceptance_criteria": [
            "All new manifests include `schema_version` attribute.",
            "Manifests without `schema_version` default to version '1.0.0' upon loading.",
            "Migration tests verify backward compatibility with historical manifests.",
        ],
        "relevant_files": [
            "src/adaptive_rl/experiments/manager.py",
            "tests/test_experiment_manager.py",
        ],
        "notes": "Guarantees long-term readability of saved benchmark archives.",
    },
    {
        "num": 19,
        "domain": "Experiment Management",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["experiments", "robustness"],
        "title": "Add atomic manifest writes and file locking for concurrent multi-seed experiment execution",
        "problem": "When running concurrent experiments or benchmarks, writing manifests directly to disk without atomic renames can result in partially-written, corrupt JSON files if interrupted.",
        "current_state": "In `src/adaptive_rl/experiments/manager.py:83`, `manifest.save()` opens the target path directly with `w` mode and writes JSON synchronously.",
        "proposed_change": "Write manifest JSON to a temporary file (`manifest.json.tmp`) in the same directory and execute an atomic `os.replace` to ensure all writes are atomic.",
        "scope": "Applies to `ExperimentManifest.save()`, `metrics.json`, and comparison report file writes.",
        "acceptance_criteria": [
            "Manifest and metrics file writes use atomic temporary-file-and-replace semantics.",
            "Interrupted writes leave previous valid files intact without partial JSON syntax errors.",
            "Unit tests simulate process interruption and verify file integrity.",
        ],
        "relevant_files": [
            "src/adaptive_rl/experiments/manager.py",
            "src/adaptive_rl/benchmarking/__init__.py",
            "tests/test_experiment_manager.py",
        ],
        "notes": "Prevents corrupt experiment results on high-throughput clusters.",
    },
    {
        "num": 20,
        "domain": "Experiment Management",
        "milestone": "Phase 18 — Reliability & Reproducibility",
        "labels": ["experiments", "provenance"],
        "title": "Record execution duration, completed timestamp, and CLI command string in ExperimentManifest",
        "problem": "`ExperimentManifest` records start time but omits total wall-clock execution time, completion timestamp, and the exact CLI invocation command.",
        "current_state": "In `src/adaptive_rl/experiments/manager.py:569–605`, `_make_manifest` captures `created_at` but no timing duration or command-line strings.",
        "proposed_change": "Add `duration_seconds: float`, `completed_at: str`, and `cli_command: Optional[str]` to `ExperimentManifest`, populating them upon experiment completion.",
        "scope": "Modifies `manager.py` execution wrappers and surfaces duration in dashboard inspections.",
        "acceptance_criteria": [
            "Manifests record `duration_seconds` and ISO UTC `completed_at` timestamps.",
            "CLI runs store the exact command-line invocation string.",
            "`adaptive-rl experiment inspect` displays run duration and command line.",
            "Tests in `tests/test_experiment_manager.py` verify timing attributes.",
        ],
        "relevant_files": [
            "src/adaptive_rl/experiments/manager.py",
            "src/adaptive_rl/cli.py",
            "src/adaptive_rl/visualization/dashboard.py",
            "tests/test_experiment_manager.py",
        ],
        "notes": "Crucial provenance for research reproducibility and computational budgeting.",
    },
]
